In [1]:
# import sys
# # setting path
# sys.path.append('../')

from taxbrain.taxbrain import TaxBrain
from taxbrain import report

In [2]:
tcja_ext = "github://OFRA-ORG:Tax-Calculator-thru74@tcja/taxcalc/reforms/ext.json"

######

reform_rt1_1 = """{
    "II_rt1": {"2026": 0.09},
    "PT_rt1": {"2026": 0.09}
}"""

reform_rt1_2 = """{
    "II_rt1": {"2026": 0.08},
    "PT_rt1": {"2026": 0.08}
}"""

reform_rt1_3 = """{
    "II_rt1": {"2026": 0.07},
    "PT_rt1": {"2026": 0.07}
}"""

reform_rt1_4 = """{
    "II_rt1": {"2026": 0.06},
    "PT_rt1": {"2026": 0.06}
}"""

reform_rt1_5 = """{
    "II_rt1": {"2026": 0.05},
    "PT_rt1": {"2026": 0.05}
}"""

reform_rt1_6 = """{
    "II_rt1": {"2026": 0.04},
    "PT_rt1": {"2026": 0.04}
}"""

reform_rt1_7 = """{
    "II_rt1": {"2026": 0.03},
    "PT_rt1": {"2026": 0.03}
}"""

reform_rt1_8 = """{
    "II_rt1": {"2026": 0.02},
    "PT_rt1": {"2026": 0.02}
}"""

reform_rt1_9 = """{
    "II_rt1": {"2026": 0.01},
    "PT_rt1": {"2026": 0.01}
}"""

######

reform_rt2_1 = """{
    "II_rt2": {"2026": 0.11},
    "PT_rt2": {"2026": 0.11}
}"""

reform_rt2_2 = """{
    "II_rt2": {"2026": 0.10},
    "PT_rt2": {"2026": 0.10}
}"""

In [3]:
reform_dict1 = {
    "tcja_ext": tcja_ext,
    "rt1_1": reform_rt1_1,
    "rt1_2": reform_rt1_2,
    "rt1_3": reform_rt1_3,
    "rt1_4": reform_rt1_4,
    "rt1_5": reform_rt1_5,
    "rt1_6": reform_rt1_6,
    "rt1_7": reform_rt1_7,
    "rt1_8": reform_rt1_8,
    "rt1_9": reform_rt1_9
}

reform_dict2 = {
    "tcja_ext": tcja_ext,
    "rt2_1": reform_rt2_1,
    "rt2_2": reform_rt2_2
}

In [4]:
dynamic_1 = TaxBrain(2025, 2034, microdata="TMD", reform=reform_dict1, stacked=True, behavior={"sub": 0.25, "cg": -3.45})
dynamic_1.run()

In [5]:
df1 = dynamic_1.stacked_table * 1e-9
df1.to_csv('incremental rate reduction 1.csv')

In [6]:
df1

,2025,2026,2027,2028,2029,2030,2031,2032,2033,2034,2025-2034
tcja_ext,0.0,-223.066405,-228.336550,-233.580972,-225.218800,-230.153917,-235.293744,-240.401069,-245.704223,-251.262609,-2113.018289
rt1_1,0.0,-20.301462,-21.027460,-21.745337,-22.456738,-23.208572,-23.978008,-24.742379,-25.557759,-26.368005,-209.385721
rt1_2,0.0,-20.229089,-20.664744,-21.681932,-22.383035,-22.857413,-23.925133,-24.614147,-25.540588,-26.311052,-208.207133
rt1_3,0.0,-20.126634,-20.919261,-21.600869,-22.076143,-23.059119,-23.841278,-24.635175,-25.365174,-26.230080,-207.853733
rt1_4,0.0,-20.039123,-20.787587,-21.462884,-22.150952,-22.634284,-23.726672,-24.501186,-25.286118,-26.113323,-206.702128
rt1_5,0.0,-19.934696,-20.650098,-21.347578,-22.105226,-22.522322,-23.614458,-24.398707,-24.963791,-25.958602,-205.495478
rt1_6,0.0,-19.742010,-20.482171,-21.212345,-21.921029,-22.634162,-23.265851,-24.172941,-24.958306,-25.727790,-204.116605
rt1_7,0.0,-19.508018,-20.304017,-20.998003,-21.708044,-22.445425,-23.185395,-23.939431,-24.473156,-25.513263,-202.074753
rt1_8,0.0,-19.309487,-20.067091,-20.723204,-21.432974,-22.195355,-22.955784,-23.627282,-24.439076,-25.257882,-200.008135
rt1_9,0.0,-18.754357,-19.842158,-20.517533,-21.196821,-21.909891,-22.351386,-23.410177,-24.176597,-24.935513,-197.094432
Total,0.0,-401.011281,-413.081137,-424.870658,-422.649762,-433.620461,-446.137709,-458.442494,-470.464788,-483.678119,-3953.956407

In [7]:
dynamic_2 = TaxBrain(2025, 2034, microdata="TMD", reform=reform_dict2, stacked=True, behavior={"sub": 0.25, "cg": -3.45})
dynamic_2.run()

In [8]:
df2 = dynamic_2.stacked_table * 1e-9
df2.to_csv('incremental rate reduction 2.csv')

In [9]:
df2

,2025,2026,2027,2028,2029,2030,2031,2032,2033,2034,2025-2034
tcja_ext,0.0,-223.066405,-228.336550,-233.580972,-225.218800,-230.153917,-235.293744,-240.401069,-245.704223,-251.262609,-2113.018289
rt2_1,0.0,-39.701357,-41.097692,-42.981342,-44.606335,-46.046006,-48.119430,-49.820332,-51.693268,-53.559699,-417.625460
rt2_2,0.0,-39.847092,-41.514935,-43.160536,-44.570589,-46.233556,-48.330489,-50.089694,-51.826769,-53.676175,-419.249835
Total,0.0,-302.614854,-310.949177,-319.722849,-314.395725,-322.433480,-331.743662,-340.311094,-349.224260,-358.498483,-2949.893584