In [1]:
# import sys
# # setting path
# sys.path.append('../')

from taxbrain.taxbrain import TaxBrain
from taxbrain import report

In [2]:
tcja_ext = "github://OFRA-ORG:Tax-Calculator-thru74@tcja/taxcalc/reforms/ext.json"

######

reform_rt1_1 = """{
    "II_rt1": {"2026": 0.09},
    "PT_rt1": {"2026": 0.09}
}"""

reform_rt1_2 = """{
    "II_rt1": {"2026": 0.08},
    "PT_rt1": {"2026": 0.08}
}"""

reform_rt1_3 = """{
    "II_rt1": {"2026": 0.07},
    "PT_rt1": {"2026": 0.07}
}"""

reform_rt1_4 = """{
    "II_rt1": {"2026": 0.06},
    "PT_rt1": {"2026": 0.06}
}"""

reform_rt1_5 = """{
    "II_rt1": {"2026": 0.05},
    "PT_rt1": {"2026": 0.05}
}"""

reform_rt1_6 = """{
    "II_rt1": {"2026": 0.04},
    "PT_rt1": {"2026": 0.04}
}"""

reform_rt1_7 = """{
    "II_rt1": {"2026": 0.03},
    "PT_rt1": {"2026": 0.03}
}"""

reform_rt1_8 = """{
    "II_rt1": {"2026": 0.02},
    "PT_rt1": {"2026": 0.02}
}"""

reform_rt1_9 = """{
    "II_rt1": {"2026": 0.01},
    "PT_rt1": {"2026": 0.01}
}"""

reform_rt1_10 = """{
    "II_rt1": {"2026": 0},
    "PT_rt1": {"2026": 0}
}"""

######

reform_rt2_1 = """{
    "II_rt2": {"2026": 0.11},
    "PT_rt2": {"2026": 0.11}
}"""

reform_rt2_2 = """{
    "II_rt2": {"2026": 0.10},
    "PT_rt2": {"2026": 0.10}
}"""

In [3]:
reform_dict1 = {
    "tcja_ext": tcja_ext,
    "rt1_1": reform_rt1_1,
    "rt1_2": reform_rt1_2,
    "rt1_3": reform_rt1_3,
    "rt1_4": reform_rt1_4,
    "rt1_5": reform_rt1_5,
    "rt1_6": reform_rt1_6,
    "rt1_7": reform_rt1_7,
    "rt1_8": reform_rt1_8,
    "rt1_9": reform_rt1_9,
    "rt1_10": reform_rt1_10
}

reform_dict2 = {
    "tcja_ext": tcja_ext,
    "rt2_1": reform_rt2_1,
    "rt2_2": reform_rt2_2
}

In [4]:
dynamic_1 = TaxBrain(2025, 2034, microdata="TMD", reform=reform_dict1, stacked=True, behavior={"sub": 0.25, "cg": -3.45})
dynamic_1.run()

In [5]:
df1 = dynamic_1.stacked_table * 1e-9
df1.to_csv('incremental rate reduction 1.csv')

In [6]:
df1

,2025,2026,2027,2028,2029,2030,2031,2032,2033,2034,2025-2034
tcja_ext,0.0,-220.185895,-225.107444,-230.361752,-221.756171,-226.357460,-231.374295,-236.478209,-241.481209,-246.993680,-2080.096114
rt1_1,0.0,-20.251095,-21.015402,-21.739175,-22.450437,-23.218750,-23.979593,-24.746217,-25.573847,-26.362098,-209.336614
rt1_2,0.0,-20.188890,-20.666562,-21.680746,-22.389516,-22.872844,-23.950631,-24.626985,-25.552308,-26.312969,-208.241451
rt1_3,0.0,-20.092988,-20.869286,-21.587097,-22.092737,-23.064846,-23.838842,-24.639391,-25.378640,-26.241445,-207.805273
rt1_4,0.0,-20.024511,-20.777017,-21.468275,-22.161693,-22.633118,-23.731437,-24.511717,-25.302208,-26.097798,-206.707773
rt1_5,0.0,-19.905438,-20.622675,-21.347054,-22.112269,-22.548241,-23.642310,-24.410921,-24.962546,-25.988592,-205.540046
rt1_6,0.0,-19.706411,-20.490937,-21.208631,-21.917560,-22.645969,-23.273851,-24.185563,-24.968416,-25.738093,-204.135432
rt1_7,0.0,-19.467339,-20.255806,-20.979606,-21.723736,-22.442820,-23.207298,-23.947767,-24.480311,-25.503653,-202.008336
rt1_8,0.0,-19.300547,-20.041493,-20.720697,-21.442538,-22.206089,-22.975341,-23.641568,-24.450265,-25.279004,-200.057542
rt1_9,0.0,-18.716216,-19.834118,-20.523443,-21.199105,-21.921496,-22.364742,-23.411356,-24.184856,-24.952355,-197.107687
rt1_10,0.0,-18.862824,-19.571952,-19.975163,-21.015745,-21.732607,-22.443396,-23.151630,-23.928540,-24.682260,-195.364116
Total,0.0,-416.702155,-429.252692,-441.591639,-440.261508,-451.644239,-464.781736,-477.751324,-490.263145,-504.151947,-4116.400385

In [7]:
dynamic_2 = TaxBrain(2025, 2034, microdata="TMD", reform=reform_dict2, stacked=True, behavior={"sub": 0.25, "cg": -3.45})
dynamic_2.run()

In [8]:
df2 = dynamic_2.stacked_table * 1e-9
df2.to_csv('incremental rate reduction 2.csv')

In [9]:
df2

,2025,2026,2027,2028,2029,2030,2031,2032,2033,2034,2025-2034
tcja_ext,0.0,-220.185895,-225.107444,-230.361752,-221.756171,-226.357460,-231.374295,-236.478209,-241.481209,-246.993680,-2080.096114
rt2_1,0.0,-39.676368,-41.095294,-42.980697,-44.608814,-46.059274,-48.110197,-49.808994,-51.699903,-53.554427,-417.593969
rt2_2,0.0,-39.864132,-41.556736,-43.170092,-44.578510,-46.233610,-48.330956,-50.115413,-51.837240,-53.677087,-419.363776
Total,0.0,-299.726395,-307.759475,-316.512541,-310.943494,-318.650343,-327.815447,-336.402617,-345.018353,-354.225194,-2917.053858