# Revenue Estimates for TCJA Extension (with Various Scenario)

- conda env: based on taxcalc-dev that comes with the taxcalc repo
- code: fork from https://github.com/martinholmer/Tax-Calculator, and then select branch thru74
- add taxbrain code in a new folder and modify it to allow both stacked reforms and behavioral response

In [1]:
from taxbrain.taxbrain import TaxBrain
from taxbrain import report

In [3]:
reform_url = "github://OFRA-ORG:Tax-Calculator-thru74@tcja/taxcalc/reforms/ext.json"

In [2]:
## corresponding to JCT's I.A.1
json1_rates = """{
    "II_rt1": {"2026": 0.10},
    "II_brk1": {"2026": [12170.98, 24341.94, 12170.98, 17353.27, 24341.94]},
    "PT_rt1": {"2026": 0.10},
    "PT_brk1": {"2026": [12170.98, 24341.94, 12170.98, 17353.27, 24341.94]},
    "II_rt2": {"2026": 0.12},
    "II_brk2": {"2026": [49483.44, 98966.89, 49483.44, 66214.83, 98966.89]},
    "PT_rt2": {"2026": 0.12},
    "PT_brk2": {"2026": [49483.44, 98966.89, 49483.44, 66214.83, 98966.89]},
    "II_rt3": {"2026": 0.22},
    "II_brk3": {"2026": [105511.38, 211022.75, 105511.38, 105481.77, 211022.75]},
    "PT_rt3": {"2026": 0.22},
    "PT_brk3": {"2026": [105511.38, 211022.75, 105511.38, 105481.77, 211022.75]},
    "II_rt4": {"2026": 0.24},
    "II_brk4": {"2026": [201428.14, 402856.25, 201428.14, 201428.14, 402856.25]},
    "PT_rt4": {"2026": 0.24},
    "PT_brk4": {"2026": [201428.14, 402856.25, 201428.14, 201428.14, 402856.25]},
    "II_rt5": {"2026": 0.32},
    "II_brk5": {"2026": [255797.72, 511595.46, 255797.72, 255797.72, 511595.46]},
    "PT_rt5": {"2026": 0.32},
    "PT_brk5": {"2026": [255797.72, 511595.46, 255797.72, 255797.72, 511595.46]},
    "II_rt6": {"2026": 0.35},
    "II_brk6": {"2026": [639523.94, 767393.2, 383696.6, 639523.94, 767393.2]},
    "PT_rt6": {"2026": 0.35},
    "PT_brk6": {"2026": [639523.94, 767393.2, 383696.6, 639523.94, 767393.2]},
    "II_rt7": {"2026": 0.37},
    "II_brk7": {"2026": [9e+99, 9e+99, 9e+99, 9e+99, 9e+99]},
    "PT_rt7": {"2026": 0.37},
    "PT_brk7": {"2026": [9e+99, 9e+99, 9e+99, 9e+99, 9e+99]}
}"""

## corresponding to JCT's I.A.2
json2_sd = """{
    "STD": {"2026": [15339.57, 30679.14, 15339.57, 22979.74, 30679.14]}
}"""

## corresponding to JCT's I.A.3
json3_personal_exemption = """{
    "II_em": {"2026": 0.00},
    "II_em_ps": {"2026": [9e+99, 9e+99, 9e+99, 9e+99, 9e+99]}
}"""

## corresponding to JCT's I.B.1
json4_qbid = """{
    "PT_qbid_rt": {"2026": 0.20},
    "PT_qbid_taxinc_thd": {"2026": [201428.14, 402856.25, 201428.14, 201428.14, 402856.25]},
    "PT_qbid_taxinc_gap": {"2026": [50000.0, 100000.0, 50000.0, 50000.0, 100000.0]},
    "PT_qbid_w2_wages_rt": {"2026": 0.50},
    "PT_qbid_alt_w2_wages_rt": {"2026": 0.25},
    "PT_qbid_alt_property_rt": {"2026": 0.03}
}"""

## corresponding to JCT's I.B.2
json5_excess_biz_loss = """{
   "ALD_BusinessLosses_c": {"2026": [319821.19, 639642.39, 319821.19, 319821.19, 639642.39]}
}"""

## corresponding to JCT's I.C.1
json6_ctc = """{
    "CTC_c": {"2026": 2000.00},
    "ACTC_c": {"2026": 1600.00},
    "CTC_ps": {"2026": [200000.0, 400000.0, 200000.0, 200000.0, 400000.0]},
    "ACTC_Income_thd": {"2026": 2500.00}
}"""

## corresponding to JCT's I.C.2
json7_odc = """{
    "ODC_c": {"2026": 500.00}
}"""

## corresponding to JCT's I.D.1 to I.D.3
json8_id = """{
    "ID_AllTaxes_c": {"2026": [10000.0, 10000.0, 5000.0, 10000.0, 10000.0]},
    "ID_Charity_crt_cash": {"2026": 0.60},
    "ID_Casualty_hc": {"2026": 1.00},
    "ID_Miscellaneous_hc": {"2026": 1.00},
    "ID_ps": {"2026": [9e+99, 9e+99, 9e+99, 9e+99, 9e+99]},
    "ID_prt": {"2026": 0.00},
    "ID_crt": {"2026": 1.00}
}"""

## JCT's I.D.4 and I.D.7 are minor and not modeled

## JCT's I.D.5 and I.D.6 don't seem to have a counterpart in the ext.json file

## JCT's I.E is minor and not modeled

## JCT's I.F doesn't seem to have a counterpart in the ext.json file

## corresponding to JCT's I.G
json9_amt = """{
    "AMT_em": {"2026": [89905.29, 139892.17, 69946.08, 89905.29, 139892.17]},
    "AMT_em_ps": {"2026": [639523.94, 1279047.88, 639523.94, 639523.94, 1279047.88]},
    "AMT_em_pe": {"2026": 939533.04}
}"""

## corresponding to JCT's II.E.1
json10_ald_domesticprod = """{
   "ALD_DomesticProduction_hc": {"2026": 1.00}
}"""

reform_dict = {
    "Brackets and rates change": json1_rates,
    "Standard deduction increase": json2_sd,
    "Personal exemption repeal": json3_personal_exemption,
    "QBID": json4_qbid,
    "Excess business losses deduction cap": json5_excess_biz_loss,
    "CTC increase": json6_ctc,
    "Other dependent credit": json7_odc,
    "Itemized deduction repeal": json8_id,
    "AMT change": json9_amt,
    "Domestic production deduction repeal": json10_ald_domesticprod
}

## 1. Revenue loss from TCJA extension, as is

**Bottom line:**
 - No behavioral response: -3.25T
 - Modest behavioral response: -2.56T
 - Larger behavioral response: -1.86T

### 1.0. Rev estimate (unstacked benchmark)

In [4]:
static = TaxBrain(2026, 2035, microdata="TMD", reform=reform_url)
static.run()
result_df = static.weighted_totals("combined") * 1e-12
diff = result_df.iloc[2].sum(axis=0)
print("Revenue difference: " + str(diff))
print("=====================")
print("Revenue table:")
result_df

Revenue difference: -3.2516540214800616
=====================
Revenue table:

,2026,2027,2028,2029,2030,2031,2032,2033,2034,2035
Base,4.552992,4.742020,4.935232,5.142649,5.356721,5.578357,5.806939,6.040037,6.278474,6.524738
Reform,4.267077,4.447848,4.632875,4.831295,5.036466,5.249092,5.468640,5.692602,5.921847,6.158764
Difference,-0.285916,-0.294172,-0.302357,-0.311354,-0.320255,-0.329266,-0.338299,-0.347435,-0.356628,-0.365974

### 1.1. Rev estimate without behavioral response (sub = 0)

In [5]:
dynamic_min = TaxBrain(2026, 2035, microdata="TMD", reform=reform_dict, stacked=True, behavior={"sub": 0})
dynamic_min.run()
dynamic_min.stacked_table * 1e-12

,2026,2027,2028,2029,2030,2031,2032,2033,2034,2035,2026-2035
Brackets and rates change,-0.210675,-0.219316,-0.227950,-0.237099,-0.246368,-0.255910,-0.265694,-0.275627,-0.285744,-0.296127,-2.520511
Standard deduction increase,-0.112658,-0.116110,-0.119322,-0.122698,-0.126178,-0.129731,-0.133311,-0.136984,-0.140727,-0.144543,-1.282262
Personal exemption repeal,0.160328,0.165724,0.170740,0.175857,0.181098,0.186466,0.191876,0.197379,0.202945,0.208562,1.840977
QBID,-0.066783,-0.069318,-0.071826,-0.074482,-0.077147,-0.079913,-0.082805,-0.085784,-0.088843,-0.091988,-0.788889
Excess business losses deduction cap,0.014326,0.014674,0.015108,0.015612,0.016112,0.016647,0.017253,0.017862,0.018508,0.019165,0.165268
CTC increase,-0.080258,-0.081752,-0.083027,-0.084263,-0.085447,-0.086562,-0.087625,-0.088630,-0.089567,-0.090434,-0.857565
Other dependent credit,-0.006789,-0.006852,-0.006902,-0.006940,-0.006982,-0.007023,-0.007055,-0.007083,-0.007102,-0.007113,-0.069840
Itemized deduction repeal,0.071106,0.075609,0.080120,0.084688,0.089552,0.094645,0.100007,0.105488,0.111149,0.117078,0.929442
AMT change,-0.059739,-0.062284,-0.064975,-0.067939,-0.071047,-0.074296,-0.077625,-0.081015,-0.084493,-0.088116,-0.731530
Domestic production deduction repeal,0.005227,0.005454,0.005678,0.005910,0.006154,0.006410,0.006680,0.006957,0.007245,0.007542,0.063258
Total,-0.285916,-0.294172,-0.302357,-0.311354,-0.320255,-0.329266,-0.338299,-0.347435,-0.356628,-0.365974,-3.251654

### 1.2. Rev estimate mild behavioral response sub = 0.25

In [6]:
dynamic_med = TaxBrain(2026, 2035, microdata="TMD", reform=reform_dict, stacked=True, behavior={"sub": 0.25})
dynamic_med.run()
dynamic_med.stacked_table * 1e-12

,2026,2027,2028,2029,2030,2031,2032,2033,2034,2035,2026-2035
Brackets and rates change,-0.171796,-0.179241,-0.186089,-0.193829,-0.201474,-0.209366,-0.217218,-0.225581,-0.233649,-0.242718,-2.060962
Standard deduction increase,-0.111024,-0.114226,-0.117680,-0.120949,-0.123938,-0.128086,-0.131387,-0.134995,-0.138694,-0.142318,-1.263296
Personal exemption repeal,0.161503,0.167247,0.172662,0.178224,0.183188,0.189140,0.194197,0.200116,0.205490,0.211687,1.863453
QBID,-0.066833,-0.069368,-0.071847,-0.074552,-0.077077,-0.079693,-0.082658,-0.085539,-0.088646,-0.091720,-0.787933
Excess business losses deduction cap,0.013877,0.014231,0.014653,0.015156,0.015650,0.016173,0.016755,0.017351,0.017986,0.018626,0.160457
CTC increase,-0.080103,-0.081711,-0.083178,-0.084655,-0.085998,-0.087351,-0.088493,-0.089732,-0.090817,-0.091840,-0.863878
Other dependent credit,-0.006869,-0.006946,-0.007020,-0.007084,-0.007093,-0.007142,-0.007006,-0.007222,-0.007010,-0.007290,-0.070683
Itemized deduction repeal,0.071481,0.075919,0.080426,0.085030,0.089694,0.094668,0.100148,0.105713,0.111558,0.117405,0.932043
AMT change,-0.044220,-0.045980,-0.047923,-0.049901,-0.051977,-0.054094,-0.056518,-0.058854,-0.061262,-0.063929,-0.534658
Domestic production deduction repeal,0.005214,0.005459,0.005659,0.005877,0.006121,0.006352,0.006586,0.006828,0.007110,0.007409,0.062615
Total,-0.228772,-0.234615,-0.240338,-0.246683,-0.252905,-0.259400,-0.265594,-0.271915,-0.277933,-0.284689,-2.562843

### 1.3. Rev estimate larger behavioral response sub = 0.5

In [7]:
dynamic_max = TaxBrain(2026, 2035, microdata="TMD", reform=reform_dict, stacked=True, behavior={"sub": 0.5})
dynamic_max.run()
dynamic_max.stacked_table * 1e-12

,2026,2027,2028,2029,2030,2031,2032,2033,2034,2035,2026-2035
Brackets and rates change,-0.131951,-0.138133,-0.143146,-0.149476,-0.155435,-0.161583,-0.167500,-0.174225,-0.180214,-0.187884,-1.589547
Standard deduction increase,-0.108423,-0.111281,-0.114988,-0.118085,-0.120496,-0.125316,-0.128421,-0.131891,-0.135532,-0.139047,-1.233478
Personal exemption repeal,0.161788,0.167852,0.173681,0.179667,0.184254,0.190866,0.195717,0.201983,0.207151,0.214076,1.877035
QBID,-0.066224,-0.068756,-0.071199,-0.073925,-0.076279,-0.078754,-0.081774,-0.084476,-0.087568,-0.090541,-0.779497
Excess business losses deduction cap,0.013492,0.013840,0.014248,0.014749,0.015238,0.015752,0.016310,0.016896,0.017524,0.018145,0.156193
CTC increase,-0.079884,-0.081638,-0.083279,-0.085005,-0.086494,-0.088093,-0.089323,-0.090793,-0.092025,-0.093280,-0.869815
Other dependent credit,-0.006939,-0.007028,-0.007122,-0.007213,-0.007197,-0.007258,-0.006963,-0.007351,-0.006894,-0.007451,-0.071415
Itemized deduction repeal,0.071747,0.076161,0.080693,0.085311,0.089763,0.094575,0.100188,0.105765,0.111797,0.117633,0.933632
AMT change,-0.029217,-0.030182,-0.031396,-0.032403,-0.033494,-0.034489,-0.036041,-0.037409,-0.038838,-0.040706,-0.344176
Domestic production deduction repeal,0.005188,0.005453,0.005633,0.005834,0.006077,0.006289,0.006483,0.006696,0.006970,0.007283,0.061907
Total,-0.170424,-0.173712,-0.176876,-0.180546,-0.184063,-0.188011,-0.191323,-0.194805,-0.197630,-0.201772,-1.859161

### 2. SALT options compared to TCJa extension, as is

**Bottom line:** 
 - Removing SALT (caps -> 0): between +0.25T (large behresp) and +0.27T (no behresp)
 - Differentiating SALT caps by filers while keeping revenue neutral relative to TCJA:
   - Single filer cap around 6,200 (and the level of behresp barely matters)
   - Joint filer cap between 12,400 (and the level of behresp barely matters)
   - Also:
     - Married filing separately and head of household treated the same as single (6,200)
     - Widows treated as joint (12,400)

#### 2.1 Removing SALT (against TCJA extension), without behavioral response

In [8]:
SALT_removal = {
    "ID_AllTaxes_c": {"2026": [0.0, 0.0, 0.0, 0.0, 0.0]},
}

In [9]:
static = TaxBrain(2026, 2035, microdata="TMD", base_policy=reform_url, reform=SALT_removal)
static.run()
result_df = static.weighted_totals("combined") * 1e-12
diff = result_df.iloc[2].sum(axis=0)
print("Revenue difference: " + str(diff))
print("=====================")
print("Revenue table:")
result_df

Revenue difference: 0.26876261375860644
=====================
Revenue table:

,2026,2027,2028,2029,2030,2031,2032,2033,2034,2035
Base,4.267077,4.447848,4.632875,4.831295,5.036466,5.249092,5.468640,5.692602,5.921847,6.158764
Reform,4.289448,4.471169,4.657180,4.856589,5.062786,5.276445,5.497044,5.722028,5.952301,6.190278
Difference,0.022371,0.023321,0.024305,0.025294,0.026320,0.027354,0.028404,0.029425,0.030455,0.031514

#### 2.2 Removing SALT (against TCJA extension), with sub = 0.25

In [11]:
static = TaxBrain(2026, 2035, microdata="TMD", base_policy=reform_url, reform=SALT_removal, behavior={"sub": 0.25})
static.run()
result_df = static.weighted_totals("combined") * 1e-12
diff = result_df.iloc[2].sum(axis=0)
print("Revenue difference: " + str(diff))
print("=====================")
print("Revenue table:")
result_df

Revenue difference: 0.26061425373731156
=====================
Revenue table:

,2026,2027,2028,2029,2030,2031,2032,2033,2034,2035
Base,4.267077,4.447848,4.632875,4.831295,5.036466,5.249092,5.468640,5.692602,5.921847,6.158764
Reform,4.288794,4.470420,4.656514,4.855825,5.061970,5.275612,5.496285,5.721213,5.951286,6.189202
Difference,0.021718,0.022572,0.023639,0.024530,0.025503,0.026520,0.027645,0.028611,0.029439,0.030438

#### 2.3 Removing SALT (against TCJA extension), with sub = 0.5

In [12]:
static = TaxBrain(2026, 2035, microdata="TMD", base_policy=reform_url, reform=SALT_removal, behavior={"sub": 0.5})
static.run()
result_df = static.weighted_totals("combined") * 1e-12
diff = result_df.iloc[2].sum(axis=0)
print("Revenue difference: " + str(diff))
print("=====================")
print("Revenue table:")
result_df

Revenue difference: 0.2537257821758125
=====================
Revenue table:

,2026,2027,2028,2029,2030,2031,2032,2033,2034,2035
Base,4.267077,4.447848,4.632875,4.831295,5.036466,5.249092,5.468640,5.692602,5.921847,6.158764
Reform,4.288243,4.469796,4.655957,4.855165,5.061272,5.274889,5.495637,5.720529,5.950432,6.188311
Difference,0.021166,0.021948,0.023083,0.023870,0.024805,0.025798,0.026997,0.027927,0.028585,0.029547

#### 2.4 Different SALT caps across filing types, without behavioral response

In [17]:
# diff = -999
# count = 0
# while diff < 0:
#     salt1 = 10000.0 - count*1000
#     SALT_adjusted = {
#         "ID_AllTaxes_c": {"2026":  [salt1, salt1*2, salt1, salt1, salt1*2]},
#     }
#     print(SALT_adjusted)
#     static = TaxBrain(2026, 2035, microdata="TMD", base_policy=reform_url, reform=SALT_adjusted)
#     static.run()
#     result_df = static.weighted_totals("combined") * 1e-12
#     diff = result_df.iloc[2].sum(axis=0)
#     print("Revenue difference is: " + str(diff))
#     count += 1

In [10]:
diff = -999
count = 0
while diff < 0:
    salt1 = 7000.0 - count*100
    SALT_adjusted = {
        "ID_AllTaxes_c": {"2026":  [salt1, salt1*2, salt1, salt1, salt1*2]},
    }
    static = TaxBrain(2026, 2035, microdata="TMD", base_policy=reform_url, reform=SALT_adjusted)
    static.run()
    result_df = static.weighted_totals("combined") * 1e-12
    diff = result_df.iloc[2].sum(axis=0)
    count += 1

print("Break-even SALT caps:")
print(SALT_adjusted)
print("Revenue difference: " + str(diff))
print("=====================")
print("Break-even revenue table:")
result_df

Break-even SALT caps:
{'ID_AllTaxes_c': {'2026': [6200.0, 12400.0, 6200.0, 6200.0, 12400.0]}}
Revenue difference: 0.0024546832396865233
=====================
Break-even revenue table:

,2026,2027,2028,2029,2030,2031,2032,2033,2034,2035
Base,4.267077,4.447848,4.632875,4.831295,5.036466,5.249092,5.468640,5.692602,5.921847,6.158764
Reform,4.267200,4.448002,4.633058,4.831508,5.036706,5.249355,5.468926,5.692911,5.922177,6.159116
Difference,0.000123,0.000154,0.000183,0.000213,0.000239,0.000264,0.000286,0.000309,0.000331,0.000352

#### 2.5 Different SALT caps across filing types, with sub = 0.25

In [16]:
# diff = -999
# count = 0
# while diff < 0:
#     salt1 = 10000.0 - count*1000
#     SALT_adjusted = {
#         "ID_AllTaxes_c": {"2026":  [salt1, salt1*2, salt1, salt1, salt1*2]},
#     }
#     print(SALT_adjusted)
#     static = TaxBrain(2026, 2035, microdata="TMD", base_policy=reform_url, reform=SALT_adjusted, behavior={"sub": 0.25})
#     static.run()
#     result_df = static.weighted_totals("combined") * 1e-12
#     diff = result_df.iloc[2].sum(axis=0)
#     print("Revenue difference is: " + str(diff))
#     count += 1

In [19]:
diff = -999
count = 0
while diff < 0:
    salt1 = 6500.0 - count*100
    SALT_adjusted = {
        "ID_AllTaxes_c": {"2026":  [salt1, salt1*2, salt1, salt1, salt1*2]},
    }
    static = TaxBrain(2026, 2035, microdata="TMD", base_policy=reform_url, reform=SALT_adjusted, behavior={"sub": 0.25})
    static.run()
    result_df = static.weighted_totals("combined") * 1e-12
    diff = result_df.iloc[2].sum(axis=0)
    count += 1

print("Break-even SALT caps:")
print(SALT_adjusted)
print("Revenue difference: " + str(diff))
print("=====================")
print("Break-even revenue table:")
result_df

Break-even SALT caps:
{'ID_AllTaxes_c': {'2026': [6200.0, 12400.0, 6200.0, 6200.0, 12400.0]}}
Revenue difference: 0.0032556541498989255
=====================
Break-even revenue table:

,2026,2027,2028,2029,2030,2031,2032,2033,2034,2035
Base,4.267077,4.447848,4.632875,4.831295,5.036466,5.249092,5.468640,5.692602,5.921847,6.158764
Reform,4.267253,4.448051,4.633130,4.831587,5.036789,5.249413,5.469027,5.693048,5.922270,6.159192
Difference,0.000176,0.000203,0.000255,0.000292,0.000323,0.000322,0.000387,0.000446,0.000424,0.000428

#### 2.5 Different SALT caps across filing types, with sub = 0.5

In [18]:
# diff = -999
# count = 0
# while diff < 0:
#     salt1 = 10000.0 - count*1000
#     SALT_adjusted = {
#         "ID_AllTaxes_c": {"2026":  [salt1, salt1*2, salt1, salt1, salt1*2]},
#     }
#     print(SALT_adjusted)
#     static = TaxBrain(2026, 2035, microdata="TMD", base_policy=reform_url, reform=SALT_adjusted, behavior={"sub": 0.5})
#     static.run()
#     result_df = static.weighted_totals("combined") * 1e-12
#     diff = result_df.iloc[2].sum(axis=0)
#     print("Revenue difference is: " + str(diff))
#     count += 1

In [15]:
diff = -999
count = 0
while diff < 0:
    salt1 = 6500.0 - count*100
    SALT_adjusted = {
        "ID_AllTaxes_c": {"2026":  [salt1, salt1*2, salt1, salt1, salt1*2]},
    }
    static = TaxBrain(2026, 2035, microdata="TMD", base_policy=reform_url, reform=SALT_adjusted, behavior={"sub": 0.5})
    static.run()
    result_df = static.weighted_totals("combined") * 1e-12
    diff = result_df.iloc[2].sum(axis=0)
    count += 1

print("Break-even SALT caps:")
print(SALT_adjusted)
print("Revenue difference: " + str(diff))
print("=====================")
print("Break-even revenue table:")
result_df

Break-even SALT caps:
{'ID_AllTaxes_c': {'2026': [6200.0, 12400.0, 6200.0, 6200.0, 12400.0]}}
Revenue difference: 0.004273654175055176
=====================
Break-even revenue table:

,2026,2027,2028,2029,2030,2031,2032,2033,2034,2035
Base,4.267077,4.447848,4.632875,4.831295,5.036466,5.249092,5.468640,5.692602,5.921847,6.158764
Reform,4.267327,4.448120,4.633200,4.831685,5.036896,5.249495,5.469157,5.693213,5.922386,6.159300
Difference,0.000250,0.000272,0.000326,0.000390,0.000429,0.000403,0.000517,0.000611,0.000539,0.000536