In [1]:
# import sys
# # setting path
# sys.path.append('../')

from taxbrain.taxbrain import TaxBrain
from taxbrain import report

In [2]:
tcja_ext = "github://OFRA-ORG:Tax-Calculator-thru74@tcja/taxcalc/reforms/ext.json"

######

reform_rt1_1 = """{
    "II_rt1": {"2026": 0.09},
    "PT_rt1": {"2026": 0.09}
}"""

reform_rt1_2 = """{
    "II_rt1": {"2026": 0.08},
    "PT_rt1": {"2026": 0.08}
}"""

reform_rt1_3 = """{
    "II_rt1": {"2026": 0.07},
    "PT_rt1": {"2026": 0.07}
}"""

reform_rt1_4 = """{
    "II_rt1": {"2026": 0.06},
    "PT_rt1": {"2026": 0.06}
}"""

reform_rt1_5 = """{
    "II_rt1": {"2026": 0.05},
    "PT_rt1": {"2026": 0.05}
}"""

reform_rt1_6 = """{
    "II_rt1": {"2026": 0.04},
    "PT_rt1": {"2026": 0.04}
}"""

reform_rt1_7 = """{
    "II_rt1": {"2026": 0.03},
    "PT_rt1": {"2026": 0.03}
}"""

reform_rt1_8 = """{
    "II_rt1": {"2026": 0.02},
    "PT_rt1": {"2026": 0.02}
}"""

reform_rt1_9 = """{
    "II_rt1": {"2026": 0.01},
    "PT_rt1": {"2026": 0.01}
}"""

reform_rt1_10 = """{
    "II_rt1": {"2026": 0},
    "PT_rt1": {"2026": 0}
}"""

values = [
    12190.93 * 2,
    24381.86 * 2,
    12190.93 * 2,
    17379.1 * 2,
    24381.86 * 2
]

reform_rt1_11 = f"""{{
    "II_brk1": {{"2026": [{values[0]},{values[1]},{values[2]},{values[3]},{values[4]}]}},
    "PT_brk1": {{"2026": [{values[0]},{values[1]},{values[2]},{values[3]},{values[4]}]}}
}}"""

######

reform_rt2_1 = """{
    "II_rt2": {"2026": 0.11},
    "PT_rt2": {"2026": 0.11}
}"""

reform_rt2_2 = """{
    "II_rt2": {"2026": 0.10},
    "PT_rt2": {"2026": 0.10}
}"""

In [3]:
reform_dict1 = {
    "tcja_ext": tcja_ext,
    "rt1_1": reform_rt1_1,
    "rt1_2": reform_rt1_2,
    "rt1_3": reform_rt1_3,
    "rt1_4": reform_rt1_4,
    "rt1_5": reform_rt1_5,
    "rt1_6": reform_rt1_6,
    "rt1_7": reform_rt1_7,
    "rt1_8": reform_rt1_8,
    "rt1_9": reform_rt1_9,
    "rt1_10": reform_rt1_10,
    "rt1_11": reform_rt1_11
}

reform_dict2 = {
    "tcja_ext": tcja_ext,
    "rt2_1": reform_rt2_1,
    "rt2_2": reform_rt2_2
}

In [4]:
dynamic_1 = TaxBrain(2025, 2034, microdata="TMD", reform=reform_dict1, stacked=True, behavior={"sub": 0.25, "cg": -3.45})
dynamic_1.run()

In [5]:
df1 = dynamic_1.stacked_table * 1e-9
df1.to_csv('incremental rate reduction 1.csv')

In [6]:
df1

,2025,2026,2027,2028,2029,2030,2031,2032,2033,2034,2025-2034
tcja_ext,0.0,-220.185895,-228.179237,-236.524948,-231.037552,-238.812369,-247.136768,-255.640162,-264.163902,-273.303187,-2194.984020
rt1_1,0.0,-20.251095,-21.002204,-21.712218,-22.417952,-22.874151,-23.926228,-24.585708,-25.506319,-26.281633,-208.557507
rt1_2,0.0,-20.188890,-20.651408,-21.653148,-22.347410,-23.124708,-23.898268,-24.657671,-25.471899,-26.218270,-208.211673
rt1_3,0.0,-20.092988,-20.852823,-21.548190,-22.048974,-22.672778,-23.764777,-24.543049,-25.281815,-26.119216,-206.924610
rt1_4,0.0,-20.024511,-20.759432,-21.438121,-22.111962,-22.900139,-23.656115,-24.430537,-25.019851,-25.998825,-206.339493
rt1_5,0.0,-19.905438,-20.610394,-21.318582,-22.051128,-22.483330,-23.553446,-24.296432,-25.014581,-25.825090,-205.058421
rt1_6,0.0,-19.706411,-20.470485,-21.172762,-21.866642,-22.568533,-23.184882,-24.079276,-24.834016,-25.586500,-203.469505
rt1_7,0.0,-19.467339,-20.238048,-20.942201,-21.674610,-22.380717,-23.109093,-23.802803,-24.337341,-25.345970,-201.298124
rt1_8,0.0,-19.300547,-20.020707,-20.681578,-21.373083,-22.129910,-22.580376,-23.572437,-24.316564,-25.130686,-199.105889
rt1_9,0.0,-18.716216,-19.823411,-20.500249,-21.160886,-21.869905,-22.609042,-23.318996,-24.049649,-24.861706,-196.910059
rt1_10,0.0,-18.862824,-19.548658,-19.940196,-20.989554,-21.683480,-22.052219,-23.060653,-23.885278,-24.551571,-194.574433
rt1_11,0.0,-192.172538,-199.462715,-207.129452,-214.207836,-221.928969,-229.513349,-237.057282,-246.164601,-253.947851,-2001.584593
Total,0.0,-608.874693,-631.619522,-654.561644,-663.287590,-685.428988,-708.984564,-733.045006,-758.045815,-783.170506,-6227.018327

In [7]:
dynamic_2 = TaxBrain(2025, 2034, microdata="TMD", reform=reform_dict2, stacked=True, behavior={"sub": 0.25, "cg": -3.45})
dynamic_2.run()

In [8]:
df2 = dynamic_2.stacked_table * 1e-9
df2.to_csv('incremental rate reduction 2.csv')

In [9]:
df2

,2025,2026,2027,2028,2029,2030,2031,2032,2033,2034,2025-2034
tcja_ext,0.0,-220.185895,-228.179237,-236.524948,-231.037552,-238.812369,-247.136768,-255.640162,-264.163902,-273.303187,-2194.984020
rt2_1,0.0,-39.676368,-41.091955,-42.972186,-44.605843,-46.065475,-48.112986,-49.816121,-51.688719,-53.524000,-417.553654
rt2_2,0.0,-39.864132,-41.556803,-43.169165,-44.567611,-46.227564,-48.321179,-50.092898,-51.841437,-53.695045,-419.335836
Total,0.0,-299.726395,-310.827995,-322.666299,-320.211007,-331.105408,-343.570934,-355.549182,-367.694058,-380.522233,-3031.873510